"project_id" : "260842" #open project settings and go to API section 
"api_token" : "5c4388fa765d071a0e087927bb13249a778cf712b48e9907c9ef25e4b4908a33d07ba8a79ed76fd8" #open profile settings and go to API & SSO > New Token > create Token
"base_path" : "client/src/localization/"
"base_url" : "https://api.crowdin.com"

"preserve_hierarchy": false

files: [
 {
    "source": "/voting.json",                              #source files filter
    "translation": "/%two_letters_code%_%original_file_name%"        #where translations are stored
  }
]