export default [
  { name: "Harstad", churchID: 36 },
  { name: "Lilongwe", churchID: 508 },
  { name: "Missouri", churchID: 60 },
  { name: "Twente", churchID: 3 },
  { name: "Bergen", churchID: 7 },
  { name: "Mumbai", churchID: 9 },
  { name: "Lilienhof", churchID: 10 },
  { name: "Cairo", churchID: 11 },
  { name: "Connecticut", churchID: 12 },
  { name: "Delaware", churchID: 15 },
  { name: "Detroit", churchID: 16 },
  { name: "Didcot", churchID: 17 },
  { name: "Drammen", churchID: 18 },
  { name: "Eiker", churchID: 20 },
  { name: "Dürrmenz", churchID: 22 },
  { name: "Mittewald", churchID: 24 },
  { name: "Graz", churchID: 26 },
  { name: "Grenland", churchID: 27 },
  { name: "Groningen", churchID: 29 },
  { name: "Gross-Godems", churchID: 30 },
  { name: "Hallingdal", churchID: 32 },
  { name: "Hamar", churchID: 33 },
  { name: "Hamburg", churchID: 34 },
  { name: "Exter", churchID: 35 },
  { name: "Hessenhöfe", churchID: 39 },
  { name: "Holstebro", churchID: 40 },
  { name: "Hong Kong", churchID: 41 },
  { name: "Horten", churchID: 42 },
  { name: "Hønefoss", churchID: 43 },
  { name: "Israel", churchID: 44 },
  { name: "Istanbul", churchID: 45 },
  { name: "Bafoussam", churchID: 46 },
  { name: "Nyakweri", churchID: 47 },
  { name: "Raumberg", churchID: 48 },
  { name: "Sørlandet", churchID: 49 },
  { name: "Kyrkslätt", churchID: 50 },
  { name: "København", churchID: 51 },
  { name: "Lahti", churchID: 52 },
  { name: "Linnenbach", churchID: 54 },
  { name: "Malinka", churchID: 55 },
  { name: "Maubach", churchID: 57 },
  { name: "Melbourne", churchID: 58 },
  { name: "Zeeland-Belgie", churchID: 59 },
  { name: "Molde", churchID: 61 },
  { name: "Missoula", churchID: 62 },
  { name: "Måløy", churchID: 64 },
  { name: "Utrecht", churchID: 66 },
  { name: "Novo Sarandi", churchID: 67 },
  { name: "Oslo/Follo", churchID: 69 },
  { name: "Ottawa", churchID: 70 },
  { name: "Paso Flores", churchID: 72 },
  { name: "Fulda", churchID: 73 },
  { name: "Rotterdam", churchID: 76 },
  { name: "Salem", churchID: 77 },
  { name: "Sandefjord", churchID: 78 },
  { name: "Sardinia", churchID: 80 },
  { name: "Seattle", churchID: 83 },
  { name: "Singapore", churchID: 84 },
  { name: "Schweiz", churchID: 86 },
  { name: "St. Petersburg", churchID: 87 },
  { name: "Stavanger", churchID: 88 },
  { name: "Stord", churchID: 90 },
  { name: "Sydney", churchID: 92 },
  { name: "Syracuse", churchID: 93 },
  { name: "Huntworth", churchID: 95 },
  { name: "Terwolde", churchID: 96 },
  { name: "Toronto", churchID: 97 },
  { name: "Tønsberg", churchID: 101 },
  { name: "Urbana", churchID: 102 },
  { name: "Usselo", churchID: 103 },
  { name: "Vácduka", churchID: 104 },
  { name: "Valdivia", churchID: 105 },
  { name: "Vancouver", churchID: 106 },
  { name: "Varna", churchID: 107 },
  { name: "Nancy", churchID: 109 },
  { name: "Waldhausen", churchID: 110 },
  { name: "Waltrop", churchID: 111 },
  { name: "Winnipeg", churchID: 114 },
  { name: "Wien", churchID: 116 },
  { name: "Wroclaw", churchID: 117 },
  { name: "Østfold", churchID: 119 },
  { name: "Valdres", churchID: 122 },
  { name: "Schermer", churchID: 125 },
  { name: "São Paulo - Cabreúva", churchID: 145 },
  { name: "New Zealand", churchID: 147 },
  { name: "Horetice", churchID: 150 },
  { name: "Kroatia", churchID: 151 },
  { name: "Paradera", churchID: 165 },
  { name: "Paris", churchID: 168 },
  { name: "Nimes", churchID: 169 },
  { name: "Steinseltz", churchID: 170 },
  { name: "Palmi", churchID: 171 },
  { name: "Shanghai", churchID: 172 },
  { name: "Slovenia", churchID: 205 },
  { name: "Etiopia", churchID: 225 },
  { name: "Shenzhen", churchID: 267 },
  { name: "Estland", churchID: 286 },
  { name: "A-lag Brunstad", churchID: 287 },
  { name: "Ozornoe", churchID: 305 },
  { name: "Malaga", churchID: 325 },
  { name: "Flevoland", churchID: 326 },
  { name: "Crasna", churchID: 327 },
  { name: "Brasov", churchID: 345 },
  { name: "Lima", churchID: 367 },
  { name: "Zhitkovichi", churchID: 369 },
  { name: "Slobozia Mare", churchID: 370 },
  { name: "Bangalore", churchID: 371 },
  { name: "Trivandrum", churchID: 372 },
  { name: "Alwaye", churchID: 376 },
  { name: "Mallorca", churchID: 377 },
  { name: "Padej", churchID: 379 },
  { name: "Medias", churchID: 380 },
  { name: "Ilo", churchID: 381 },
  { name: "Leon", churchID: 382 },
  { name: "Pune", churchID: 383 },
  { name: "Mersin", churchID: 384 },
  { name: "Jakarta", churchID: 385 },
  { name: "Dubai", churchID: 387 },
  { name: "Colombo", churchID: 388 },
  { name: "Adjud", churchID: 390 },
  { name: "Caragiale", churchID: 391 },
  { name: "Bucharest", churchID: 392 },
  { name: "Cràiova", churchID: 394 },
  { name: "Giurgiu", churchID: 395 },
  { name: "Dorohoi", churchID: 396 },
  { name: "Catania", churchID: 398 },
  { name: "Curico", churchID: 399 },
  { name: "Sofia", churchID: 400 },
  { name: "Dobarsko", churchID: 401 },
  { name: "Blagoevgrad", churchID: 402 },
  { name: "Debrecen", churchID: 405 },
  { name: "Inke", churchID: 406 },
  { name: "Bakonycsernye", churchID: 407 },
  { name: "Majlat", churchID: 409 },
  { name: "Thailand", churchID: 414 },
  { name: "Yaoundé", churchID: 424 },
  { name: "Ternopol", churchID: 427 },
  { name: "Beljaevka", churchID: 428 },
  { name: "Kharkov", churchID: 429 },
  { name: "Zakarpattia", churchID: 430 },
  { name: "Cherkassy", churchID: 431 },
  { name: "Reni", churchID: 432 },
  { name: "Tudora", churchID: 433 },
  { name: "BCC", churchID: 435 },
  { name: "Kreta", churchID: 439 },
  { name: "Goa", churchID: 440 },
  { name: "Coimbatore", churchID: 441 },
  { name: "Langtore", churchID: 443 },
  { name: "New Delhi", churchID: 444 },
  { name: "Douala", churchID: 445 },
  { name: "Bishkek", churchID: 446 },
  { name: "Mwanza", churchID: 447 },
  { name: "Congo", churchID: 448 },
  { name: "Villa Regina", churchID: 450 },
  { name: "Para", churchID: 451 },
  { name: "A-lag MOBILT", churchID: 452 },
  { name: "Arequipa", churchID: 455 },
  { name: "Kisii", churchID: 456 },
  { name: "Kisumu", churchID: 457 },
  { name: "Santa Rosa", churchID: 458 },
  { name: "Brunstad", churchID: 459 },
  { name: "Porto Alegre", churchID: 469 },
  { name: "Rodi Kopany", churchID: 471 },
  { name: "Central Russia", churchID: 473 },
  { name: "Mulanje", churchID: 475 },
  { name: "Nairobi", churchID: 476 },
  { name: "Uganda", churchID: 478 },
  { name: "A-team Vanderbijlpark", churchID: 479 },
  { name: "New Church", churchID: 422 },
  { name: "New Church", churchID: 423 },
  { name: "New Church", churchID: 434 },
  { name: "New Church", churchID: 436 },
  { name: "UTGÅR", churchID: 437 },
  { name: "Abu Dhabi", churchID: 1 },
  { name: "Berlin", churchID: 8 },
  { name: "Curupaity", churchID: 13 },
  { name: "Esbjerg", churchID: 23 },
  { name: "Hallau", churchID: 31 },
  { name: "Mansfeld", churchID: 56 },
  { name: "Trondheim", churchID: 98 },
  { name: "De Wijk", churchID: 108 },
  { name: "Wisconsin", churchID: 115 },
  { name: "Østerrike", churchID: 124 },
  { name: "A-lag  Queck", churchID: 461 },
  { name: "A-lag Connecticut", churchID: 463 },
  { name: "A-lag Didcot", churchID: 466 },
  { name: "A-lag Hamar", churchID: 468 },
  { name: "A-lag Oslo", churchID: 460 },
  { name: "A-lag Pagedal", churchID: 465 },
  { name: "A-team Pagedal", churchID: 418 },
  { name: "A-Team Exter", churchID: 506 },
  { name: "Weißbach", churchID: 112 },
  { name: "Herford", churchID: 38 },
  { name: "Ober-Erlenbach", churchID: 68 },
  { name: "Scheppach", churchID: 81 },
  { name: "Ciocanesti", churchID: 389 },
  { name: "Iasi", churchID: 393 },
  { name: "Kanpur", churchID: 449 },
  { name: "Stockholm", churchID: 89 },
  { name: "Trysil", churchID: 99 },
  { name: "Bariloche", churchID: 5 },
  { name: "Sdr. Jylland", churchID: 82 },
  { name: "Vänersborg", churchID: 85 },
  { name: "Tunis", churchID: 100 },
  { name: "Yakima", churchID: 118 },
  { name: "Queensland", churchID: 120 },
  { name: "Esquel", churchID: 472 },
  { name: "Växsjö", churchID: 149 },
  { name: "Joensuu", churchID: 167 },
  { name: "Kuwait", churchID: 146 },
  { name: "Perth", churchID: 265 },
  { name: "Ukraina", churchID: 410 },
  { name: "Kirkenes", churchID: 507 },
  { name: "Island", churchID: 509 },
  { name: "Rome", churchID: 397 },
  { name: "Tulsa,", churchID: 368 },
  { name: "South Africa", churchID: 373 },
  { name: "Pretoria", churchID: 374 },
  { name: "Cape Town", churchID: 375 },
  { name: "Pluto", churchID: 511 },
  { name: "Moss", churchID: 510 },
  { name: "Administration", churchID: 453 },
  { name: "Svartskog", churchID: 505 },
  { name: "Hobbiton", churchID: 512 }
]
